# Generated by Django 5.2.17 on 2026-09-02 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("workorders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("status_changed", "Status Changed"),
                            ("note_added", "Note Added"),
                            ("arrived", "Arrived"),
                            ("work_started", "Work Started"),
                            ("work_completed", "Work Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("raw_request", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_events",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_events",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "work_order"],
                        name="events_prog_organis_00c56b_idx",
                    ),
                    models.Index(
                        fields=["organisation", "event_id"],
                        name="events_prog_organis_038de3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "event_id"), name="uniq_org_event_id"
                    )
                ],
            },
        ),
    ]
